# Fault System Configuration for Eagle West Field MRST Simulation
# Source: 01_Structural_Geology.md (CANON)
# Compatible with s04_add_faults.m requirements
# Date: 2025-08-07
# Fixed: 2025-08-10 - Converted mixed YAML format to consistent structure format

fault_system:
  # Major Fault System (CANON from 01_Structural_Geology.md Section 2.2)
  faults:
    # Named structure compatible with YAML parser (similar to wells)
    
    Fault_A:
      # Fault A - Northern Boundary (CANON Section 2.2)
      name: "Fault_A"
      type: "normal_with_reverse_component"
      is_sealing: true
      strike: 65.0                      # degrees (N65°E)
      dip: 70.0                         # degrees SE
      length: 2500.0                    # ft (scaled for field size: 3280×2950 ft)
      transmissibility_multiplier: 0.005
      position_offset_x: 0.0            # ft from bounds origin
      position_offset_y: 800.0          # ft north offset (reduced to keep within field)
      throw_average: 150.0              # ft (120-180 range)
      sealing_character: "sealing"
      shale_gouge_ratio: 0.25           # >20% indicates sealing
      
    Fault_B:
      # Fault B - Eastern Boundary (CANON Section 2.2)
      name: "Fault_B"
      type: "normal"
      is_sealing: false
      strike: 20.0                      # degrees (N20°E)
      dip: 65.0                         # degrees NW
      length: 2200.0                    # ft (scaled for field size: 3280×2950 ft)
      transmissibility_multiplier: 0.05
      position_offset_x: 900.0          # ft east offset (reduced to keep within field)
      position_offset_y: 0.0            # ft from center
      throw_average: 110.0              # ft (80-140 range)
      sealing_character: "partially_sealing"
      shale_gouge_ratio: 0.15           # Marginal sealing
      
    Fault_C:
      # Fault C - Southern Boundary (CANON Section 2.2)
      name: "Fault_C"
      type: "normal"
      is_sealing: true
      strike: 285.0                     # degrees (N75°W = 360-75 = 285)
      dip: 62.0                         # degrees NE
      length: 1800.0                    # ft (scaled for field size: 3280×2950 ft)
      transmissibility_multiplier: 0.01
      position_offset_x: 0.0            # ft from center
      position_offset_y: -800.0         # ft south offset (reduced to keep within field)
      throw_average: 127.5              # ft (95-160 range)
      sealing_character: "variable_sealing"
      shale_gouge_ratio: 0.20           # Central portion sealing
      
    # Fault D - Western Boundary (CANON Section 2.2)
    Fault_D:
      name: "Fault_D"
      type: "normal_growth_fault"
      is_sealing: true
      strike: 345.0                     # degrees (N15°W = 360-15 = 345)
      dip: 68.0                         # degrees NE
      length: 2100.0                    # ft (scaled for field size: 3280×2950 ft)
      transmissibility_multiplier: 0.005
      position_offset_x: -900.0         # ft west offset (reduced to keep within field)
      position_offset_y: 0.0            # ft from center
      throw_average: 155.0              # ft (110-200 range)
      sealing_character: "sealing"
      shale_gouge_ratio: 0.30           # Good sealing capacity
      
    # Fault E - Internal Compartment (CANON Section 2.2)
    Fault_E:
      name: "Fault_E"
      type: "normal_internal"
      is_sealing: false
      strike: 45.0                      # degrees (N45°E)
      dip: 72.0                         # degrees SE
      length: 1400.0                    # ft (scaled for field size: 3280×2950 ft)
      transmissibility_multiplier: 0.3
      position_offset_x: 410.0          # ft east offset (internal)
      position_offset_y: 370.0          # ft north offset
      throw_average: 60.0               # ft (40-80 range)
      sealing_character: "partially_sealing"
      shale_gouge_ratio: 0.12           # Creates compartmentalization
      
  # System Properties
  fault_system_properties:
    total_faults: 5
    compartments_created: 2             # Northern and Southern
    dominant_fault_trend: "NE-SW"       # Regional extensional system
    fault_age: "syn_depositional"       # Growth faults active during deposition
    
    # Grid Impact Parameters
    grid_refinement_buffer: 300.0       # ft around major faults
    minimum_cell_size_near_fault: 25.0  # ft (for accurate transmissibility)
    
    # Fault geometry parameters (for s05 random generation)
    displacement_base: 20.0             # Base displacement value (ft)
    displacement_variation: 10.0        # Variation range (+/-) (ft)  
    width_base: 5.0                     # Base width value (ft)
    width_variation: 3.0                # Variation range (+/-) (ft)
    
    # Validation Parameters
    seismic_validation: true
    well_control_validation: true
    pressure_data_support: true
    fault_seal_analysis_complete: true
    
# Fault Processing Thresholds (Canon-First S05 Requirements)
processing_parameters:
  # Fault detection and classification thresholds
  sealing_threshold: 0.01              # Transmissibility multiplier below which fault is considered sealing
  fault_influence_threshold: 1.0       # Transmissibility multiplier below which fault affects flow
  minimum_geometric_factor: 2.0        # Minimum geometric factor for numerical stability (ln value)

# Historical Context (CANON Documentation)
documentation_source:
  primary_document: "01_Structural_Geology.md"
  section_reference: "Section 2.2 - Major Fault Systems"
  validation_data:
    - seismic_interpretation_2019
    - well_log_correlations
    - pressure_transient_analysis
    - production_history_matching