# Fluid Properties Configuration for Eagle West Field MRST Simulation
# Source: 03_Fluid_Properties.md (CANON)
# Compatible with s02_define_fluids.m requirements
# Date: 2025-08-07

fluid_properties:
  # Basic Fluid Properties (s03 required format)
  oil_density: 865.0                    # kg/m³ (API 32°, SG 0.865)
  water_density: 1025.0                 # kg/m³ (SG 1.025) 
  gas_density: 0.8                      # kg/m³ at standard conditions
  
  oil_viscosity: 0.92                   # cp at bubble point conditions (2100 psi, 176°F)
  water_viscosity: 0.385                # cp at reservoir conditions (176°F)
  gas_viscosity: 0.02                   # cp at reservoir conditions
  
  bubble_point: 2100.0                  # psi @ 176°F (CANON)
  solution_gor: 450.0                   # scf/STB (initial GOR, CANON)
  reservoir_temperature: 176.0          # °F (constant, CANON)
  initial_reservoir_pressure: 2900.0    # psi (CANON)
  
  # API and Specific Gravity (CANON from 03_Fluid_Properties.md)
  api_gravity: 32.0                     # °API
  oil_specific_gravity: 0.865           # Oil SG
  water_specific_gravity: 1.025         # Water SG
  gas_specific_gravity: 0.785           # Gas SG (air = 1.0)
  
  # Water Properties (CANON)
  water_salinity: 35000                 # ppm TDS (NaCl equivalent)
  formation_water_type: "NaCl_brine"
  
  # Surface Conditions (CANON)
  surface_temperature: 60.0             # °F (standard conditions)
  surface_pressure: 14.7                # psia (standard conditions)
  
  # Reservoir Conditions (CANON)
  reservoir_depth: 8000.0               # ft datum
  pressure_gradient: 0.433              # psi/ft
  fluid_type: "black_oil"              # 3-phase system
  initial_fluid_state: "undersaturated_oil"
  
  # Complete PVT Tables (CANON from 03_Fluid_Properties.md) 
  # Oil Bo Table (s03 expected format)
  oil_bo_pressure_table:
    pressures: [500, 1000, 1500, 2000, 2100, 2200, 2500, 3000, 3500, 4000]
    bo_values: [1.125, 1.185, 1.245, 1.295, 1.305, 1.301, 1.295, 1.285, 1.275, 1.265]
    
  # Solution GOR Table (s03 expected format)
  solution_gor_table:
    rs_values: [195, 285, 365, 435, 450, 450, 450, 450, 450, 450]
    
  # Oil Viscosity Table (s03 expected format)  
  oil_viscosity_table:
    viscosity_values: [1.85, 1.45, 1.15, 0.95, 0.92, 0.94, 0.98, 1.05, 1.12, 1.18]
    
  # Oil Compressibility (CANON)
  oil_compressibility:
    pressure_ranges: [[500, 1000], [1000, 1500], [1500, 2000], [2000, 2500], [2500, 3000], [3000, 3500], [3500, 4000]]
    co_values: [28.5e-6, 22.1e-6, 18.3e-6, 15.8e-6, 14.2e-6, 13.1e-6, 12.3e-6]  # 1/psi
    
  # Gas Bg Table (s03 expected format)
  gas_bg_pressure_table:
    pressures: [500, 1000, 1500, 2000, 2500, 3000, 3500, 4000]
    bg_values: [3.850, 1.925, 1.283, 0.963, 0.770, 0.642, 0.550, 0.481]
    
  # Gas Viscosity Table (s03 expected format)
  gas_viscosity_table:
    viscosity_values: [0.0145, 0.0165, 0.0185, 0.0205, 0.0225, 0.0245, 0.0265, 0.0285]
    
    # Additional gas properties (for reference)
    z_factor: [0.892, 0.835, 0.795, 0.768, 0.750, 0.738, 0.730, 0.725]
    
  # Gas Properties (CANON)
  gas_properties:
    critical_temperature: 382.0        # °R
    critical_pressure: 665.0           # psia
    pseudo_critical_temp: 399.0        # °R
    pseudo_critical_pressure: 668.0    # psia
    composition: "methane_dominated"   # Predominantly methane with C2-C6
    viscosity_correlation: "lee_gonzalez_eakin"
    rv_dry_gas: 0.0                    # STB/Mscf for dry gas (no condensate)
    
  # Gas Compressibility (CANON)
  gas_compressibility:
    pressures: [500, 1000, 1500, 2000, 2500, 3000, 3500, 4000]
    cg_values: [1785e-6, 960e-6, 680e-6, 520e-6, 420e-6, 350e-6, 300e-6, 260e-6]  # 1/psi
    
  # Water Bw Table (s03 expected format)
  water_bw_pressure_table:
    pressures: [500, 1000, 1500, 2000, 2500, 3000, 3500, 4000]
    bw_values: [1.0385, 1.0375, 1.0365, 1.0355, 1.0345, 1.0335, 1.0325, 1.0315]
    
  # Water Compressibility Table (s03 expected format)
  water_compressibility_table:
    cw_values: [3.85e-6, 3.82e-6, 3.79e-6, 3.76e-6, 3.73e-6, 3.70e-6, 3.67e-6, 3.64e-6]
    
  # Water Properties (s03 expected format)
  water_properties:
    water_viscosity: 0.385           # cp at reservoir conditions
    water_viscosibility: 0.0         # Viscosity compressibility (usually negligible)
    
  # Field Average Properties (s03 expected format)
  field_average_properties:
    connate_water_saturation: 0.20     # Field average Swc
    residual_oil_saturation: 0.25      # Field average Sor
    residual_gas_saturation: 0.05      # Field average Sgr
    residual_oil_to_gas: 0.18          # Residual oil saturation to gas (Sorg)
    capillary_pressure_entry: 5.0      # Entry pressure for simplified model (psi)
    capillary_pressure_max: 50.0       # Maximum capillary pressure cap (psi)
    
  # RT1 Properties - Dominant Rock Type (Sandstone from SCAL documentation)
  rt1_properties:
    # Oil-Water Relative Permeability Parameters (CANON SCAL Section 1.1)
    krw_max: 0.35                       # Water relative permeability at Sor
    kro_max: 0.85                       # Oil relative permeability at Swc
    corey_water_exponent: 1.9           # Water Corey exponent (nw)
    corey_oil_exponent: 2.8             # Oil Corey exponent (no)
    
    # Gas-Oil Relative Permeability Parameters (CANON SCAL Section 1.2)
    krg_max: 0.75                       # Gas relative permeability at Sor
    krog_max: 0.82                      # Oil relative permeability at Sgc
    corey_gas_exponent: 1.6             # Gas Corey exponent (ng)
    corey_oil_gas_exponent: 2.2         # Oil Corey exponent for gas (nog)
    
  # Fluid Contacts (CANON)
  fluid_contacts:
    oil_water_contact: 8150.0          # ft TVDSS
    gas_oil_contact: null              # No initial gas cap
    initial_saturation_distribution:
      sw_initial: 0.20                 # Initial water saturation
      so_initial: 0.80                 # Initial oil saturation  
      sg_initial: 0.00                 # Initial gas saturation (no gas cap)
      
  # MRST Fluid Model Configuration
  mrst_fluid_config:
    fluid_model: "blackoil"            # MRST blackoil model
    phases: ["water", "oil", "gas"]    # 3-phase system
    pvt_method: "tabulated"            # Use tabulated PVT data
    viscosity_model: "tabulated"       # Use tabulated viscosity
    compressibility_model: "constant"  # Constant compressibility per pressure range
    
  # Validation Parameters
  validation:
    bubble_point_tolerance: 50.0       # psi (±50 psi validation range)
    pvt_data_quality: "laboratory"     # Lab-measured PVT data
    pressure_range: [500, 4000]        # psi (valid pressure range)
    temperature_constant: 176.0        # °F (isothermal conditions)