# Fluid Properties Configuration for Eagle West Field MRST Simulation
# Based on: 03_Fluid_Properties.md - Complete PVT Analysis
# Date: January 30, 2025

fluid_properties:
  # Oil properties (per 03_Fluid_Properties.md)
  oil_density: 865.0      # kg/m³ (API 32°, SG 0.865)
  oil_viscosity: 0.92     # cP at bubble point conditions (2100 psi, 176°F)
  api_gravity: 32.0       # °API
  specific_gravity: 0.865 # Oil specific gravity
  
  # Water properties (per 03_Fluid_Properties.md)
  water_density: 1025.0   # kg/m³ (SG 1.025)
  water_viscosity: 0.385  # cP at reservoir conditions (176°F)
  water_salinity: 35000   # ppm TDS (NaCl equivalent)
  water_specific_gravity: 1.025
  
  # Gas properties (per 03_Fluid_Properties.md)
  gas_density: 0.8        # kg/m³ at standard conditions
  gas_viscosity: 0.02     # cP at reservoir conditions
  gas_specific_gravity: 0.785  # (air = 1.0)
  
  # PVT properties (per 03_Fluid_Properties.md)
  bubble_point: 2100.0    # psi @ 176°F (corrected from documentation)
  solution_gor: 450.0     # scf/STB (initial GOR, corrected from documentation)
  reservoir_temperature: 176.0  # °F (constant)
  initial_reservoir_pressure: 2900.0  # psi
  
  # Complete PVT Tables from 03_Fluid_Properties.md
  
  # Oil Formation Volume Factor (Bo) vs Pressure
  oil_bo_pressure_table:
    pressures: [500, 1000, 1500, 2000, 2100, 2200, 2500, 3000, 3500, 4000]  # psi
    bo_values: [1.125, 1.185, 1.245, 1.295, 1.305, 1.301, 1.295, 1.285, 1.275, 1.265]  # rb/STB
    
  # Solution Gas-Oil Ratio (Rs) vs Pressure  
  solution_gor_table:
    pressures: [500, 1000, 1500, 2000, 2100, 2200, 2500, 3000, 3500, 4000]  # psi
    rs_values: [195, 285, 365, 435, 450, 450, 450, 450, 450, 450]  # scf/STB
    
  # Oil Viscosity (μo) vs Pressure
  oil_viscosity_table:
    pressures: [500, 1000, 1500, 2000, 2100, 2200, 2500, 3000, 3500, 4000]  # psi
    viscosity_values: [1.85, 1.45, 1.15, 0.95, 0.92, 0.94, 0.98, 1.05, 1.12, 1.18]  # cp
  
  # Oil Compressibility (Co) vs Pressure  
  oil_compressibility_table:
    pressure_ranges: [[500, 1000], [1000, 1500], [1500, 2000], [2000, 2500], [2500, 3000], [3000, 3500], [3500, 4000]]
    co_values: [28.5e-6, 22.1e-6, 18.3e-6, 15.8e-6, 14.2e-6, 13.1e-6, 12.3e-6]  # 1/psi
  
  # Gas Formation Volume Factor (Bg) vs Pressure
  gas_bg_pressure_table:
    pressures: [500, 1000, 1500, 2000, 2500, 3000, 3500, 4000]  # psi
    bg_values: [3.850, 1.925, 1.283, 0.963, 0.770, 0.642, 0.550, 0.481]  # rb/Mcf
    
  # Gas Z-Factor vs Pressure
  gas_z_factor_table:
    pressures: [500, 1000, 1500, 2000, 2500, 3000, 3500, 4000]  # psi
    z_values: [0.892, 0.835, 0.795, 0.768, 0.750, 0.738, 0.730, 0.725]
    
  # Gas Viscosity (μg) vs Pressure
  gas_viscosity_table:
    pressures: [500, 1000, 1500, 2000, 2500, 3000, 3500, 4000]  # psi
    viscosity_values: [0.0145, 0.0165, 0.0185, 0.0205, 0.0225, 0.0245, 0.0265, 0.0285]  # cp
  
  # Gas Compressibility (Cg) vs Pressure
  gas_compressibility_table:
    pressures: [500, 1000, 1500, 2000, 2500, 3000, 3500, 4000]  # psi
    cg_values: [1785e-6, 960e-6, 680e-6, 520e-6, 420e-6, 350e-6, 300e-6, 260e-6]  # 1/psi
  
  # Water Formation Volume Factor (Bw) vs Pressure
  water_bw_pressure_table:
    pressures: [500, 1000, 1500, 2000, 2500, 3000, 3500, 4000]  # psi
    bw_values: [1.0385, 1.0375, 1.0365, 1.0355, 1.0345, 1.0335, 1.0325, 1.0315]  # rb/STB
    
  # Water Compressibility (Cw) vs Pressure
  water_compressibility_table:
    pressures: [500, 1000, 1500, 2000, 2500, 3000, 3500, 4000]  # psi
    cw_values: [3.85e-6, 3.82e-6, 3.79e-6, 3.76e-6, 3.73e-6, 3.70e-6, 3.67e-6, 3.64e-6]  # 1/psi
  
  # Rock-type specific relative permeability properties (per 02_Rock_Properties.md Canon)
  # Based on rock type distribution: RT1 (layers 1-3,5-7), RT2 (layers 9-12), RT6 (layers 4,8)
  
  # RT1 - High Permeability Sandstone (dominant rock type)
  rt1_properties:
    connate_water_saturation: 0.15  # Swir for RT1 (02_Rock_Properties.md line 236)
    residual_oil_saturation: 0.25   # Sor for RT1 
    residual_gas_saturation: 0.05   # Sgr for RT1
    residual_oil_to_gas: 0.15       # Sorg for RT1
    krw_max: 0.40                   # krw@Sor for RT1
    kro_max: 0.85                   # kro@Swir for RT1
    krg_max: 0.75                   # krg@Sorg for RT1  
    krog_max: 0.90                  # krog@Sgr for RT1
    corey_water_exponent: 2.5       # nw for RT1
    corey_oil_exponent: 2.0         # no for RT1
    corey_gas_exponent: 1.8         # ng for RT1
    corey_oil_gas_exponent: 2.2     # nog for RT1
    layers: [1, 2, 3, 5, 6, 7]      # Upper and middle zone sands
  
  # RT2 - Medium Permeability Sandstone  
  rt2_properties:
    connate_water_saturation: 0.18  # Swir for RT2 (02_Rock_Properties.md line 237)
    residual_oil_saturation: 0.28   # Sor for RT2
    residual_gas_saturation: 0.08   # Sgr for RT2
    residual_oil_to_gas: 0.18       # Sorg for RT2
    krw_max: 0.35                   # krw@Sor for RT2
    kro_max: 0.80                   # kro@Swir for RT2
    krg_max: 0.68                   # krg@Sorg for RT2
    krog_max: 0.85                  # krog@Sgr for RT2
    corey_water_exponent: 2.8       # nw for RT2
    corey_oil_exponent: 2.2         # no for RT2  
    corey_gas_exponent: 2.0         # ng for RT2
    corey_oil_gas_exponent: 2.4     # nog for RT2
    layers: [9, 10, 11, 12]         # Lower zone sands
  
  # RT6 - Shale Barriers
  rt6_properties:
    connate_water_saturation: 0.35  # Swir for RT6 (high water saturation)
    residual_oil_saturation: 0.45   # Sor for RT6 (poor drainage)
    residual_gas_saturation: 0.25   # Sgr for RT6 (high gas trapping)
    residual_oil_to_gas: 0.35       # Sorg for RT6
    krw_max: 0.05                   # krw@Sor for RT6 (very low)
    kro_max: 0.25                   # kro@Swir for RT6 (very low)
    krg_max: 0.15                   # krg@Sorg for RT6 (very low)
    krog_max: 0.30                  # krog@Sgr for RT6
    corey_water_exponent: 5.0       # nw for RT6 (high tortuosity)
    corey_oil_exponent: 4.0         # no for RT6
    corey_gas_exponent: 4.0         # ng for RT6  
    corey_oil_gas_exponent: 4.5     # nog for RT6
    layers: [4, 8]                  # Shale barrier layers
  
  # Field-weighted average properties (for initialization/reference)
  field_average_properties:
    connate_water_saturation: 0.17  # Volume-weighted average
    residual_oil_saturation: 0.26   # Volume-weighted average
    residual_gas_saturation: 0.06   # Volume-weighted average
    residual_oil_to_gas: 0.16       # Volume-weighted average
  
  # Capillary pressure (estimated - not specified in documentation)
  capillary_entry_pressure: 5.0  # psi (unchanged, not in documentation)
  capillary_lambda: 2.0           # (unchanged, not in documentation)