# Fluid Properties Configuration
# This file contains fluid properties, PVT data, and relative permeability curves
# Used by: s02_define_fluid.m

# Fluid Properties (structure expected by simulation scripts)
fluid:
  # Direct parameters for simulation scripts
  oil_density: 850.0            # Oil density [kg/m続]
  water_density: 1000.0         # Water density [kg/m続]
  oil_viscosity: 2.0            # Oil viscosity [cP]
  water_viscosity: 0.5          # Water viscosity [cP]
  
  # Saturation endpoints
  connate_water_saturation: 0.15    # Swcon [-]
  residual_oil_saturation: 0.20     # Sores [-]
  
  # Detailed fluid properties
  oil:
    density: 850.0                # Oil density [kg/m続]
    viscosity: 2.0                # Oil viscosity [cP]
    formation_volume_factor: 1.2   # Oil FVF [-]
    compressibility: 1.0e-5        # Oil compressibility [1/psi]
    reference_pressure: 2900.0     # Reference pressure for PVT [psi]
    
  water:
    density: 1000.0               # Water density [kg/m続]
    viscosity: 0.5                # Water viscosity [cP]
    formation_volume_factor: 1.0   # Water FVF [-]
    compressibility: 3.0e-6        # Water compressibility [1/psi]
    reference_pressure: 2900.0     # Reference pressure for PVT [psi]
    
  # Relative permeability curves
  relative_permeability:
    hysteresis: false             # Enable hysteresis (false: no)
    
    oil:
      residual_saturation: 0.20    # Sor [-]
      endpoint_krmax: 0.90         # Maximum kro [-]
      corey_exponent: 2.0          # Corey exponent [-]
      
    water:
      connate_saturation: 0.15     # Swc [-]
      endpoint_krmax: 0.85         # Maximum krw [-]
      corey_exponent: 2.5          # Corey exponent [-]
    
    # PVT pressure range for curves
    pvt_pressure_range:
      min: 1000.0                  # Minimum pressure [psi]
      max: 5000.0                  # Maximum pressure [psi]
      num_points: 50               # Number of pressure points
    
    # Saturation range for kr curves
    saturation_range:
      num_points: 100              # Number of saturation points
      smoothing_factor: 0.1        # Smoothing factor for curves