# Grid Configuration for Eagle West Field MRST Simulation
# Simplified format for Python-MRST workflow
# Date: January 30, 2025

grid:
  # Basic grid dimensions (40x40x12 per documentation)
  nx: 40
  ny: 40
  nz: 12
  
  # Cell sizes (per MRST_Implementation.md)
  cell_size_x: 82.0  # ft
  cell_size_y: 74.0  # ft
  
  # Layer thicknesses (12 layers, 8.3 ft each per documentation)
  layer_thicknesses: [8.3, 8.3, 8.3, 8.3, 8.3, 8.3, 8.3, 8.3, 8.3, 8.3, 8.3, 8.3]
  
  # Grid origin
  origin_x: 0.0
  origin_y: 0.0
  origin_z: 8000.0  # ft TVDSS
  
# Refinement configuration (Policy 1 compliance)
refinement:
  # Well refinement parameters
  well_refinement:
    radius: 250.0  # ft - refinement radius around wells
    factor: 2      # refinement factor (2x2 subdivision)
    
  # Fault refinement parameters
  fault_refinement:
    buffer: 300.0  # ft - buffer zone around faults
    factor: 2      # refinement factor for fault zones
    apply_to_sealing_only: true  # only refine sealing faults
    
  # General refinement thresholds
  refinement_thresholds:
    max_coverage_percentage: 75.0  # max 75% cells refined (complex field)
    min_coverage_percentage: 5.0   # min 5% cells refined