# Grid Configuration for Eagle West Field MRST Simulation
# Source: 00_Overview.md, 01_Structural_Geology.md (CANON)
# Compatible with s05_create_pebi_grid.m (canonical PEBI grid implementation)
# Date: 2025-08-07
# UPDATED: 2025-08-14 - PEBI Grid Implementation with fault-conforming geometry
# REORGANIZED: 2025-08-14 - Canon-First cleanup, eliminated information duplication
#
# CANON-FIRST PRINCIPLE ENFORCED:
# - This file contains ONLY grid geometry and PEBI generation parameters
# - Well classifications: wells_config.yaml -> grid_refinement.well_tiers (CANONICAL)
# - Fault classifications: fault_config.yaml (CANONICAL)
# - NO well/fault domain information duplicated here
#
# PEBI GRID ARCHITECTURE:
# - Fault-conforming PEBI grid using MRST UPR module
# - Size-field approach with tiered well/fault influence zones
# - Natural size transitions instead of artificial subdivision
# - Faults as grid edges for proper sealing behavior
# - Target cells: ~9,660 active cells (PEBI optimized for Eagle West Field)

# Refinement Configuration (Top-level for s05_grid_refinement.m)
refinement:
  # Tiered Refinement Strategy - Phase 2 Implementation
  tiered_strategy:
    enable: true
    apply_tier_based_refinement: true
    
  # Well Area Refinement (OPTIMIZED for 25% coverage target)
  well_refinement:
    enable: true
    
    # Well refinement parameters loaded from wells_config.yaml
    # CANONICAL SOURCE: wells_config.yaml -> grid_refinement.well_tiers
    # Grid scripts must load well tier classifications from wells config
    
    # Legacy uniform refinement (used when tiered_strategy.enable = false)
    radius: 250.0                    # ft radius around wellbores
    factor: 2                        # refinement factor (2x2 subdivision)
    refined_cell_size_x: 20.0        # ft (refined cell E-W)
    refined_cell_size_y: 18.0        # ft (refined cell N-S)  
    refined_layer_thickness: 4.0     # ft (refined vertical)
    transition_smooth: true
    
  # Fault Area Refinement (OPTIMIZED for 25% coverage target)
  fault_refinement:
    enable: true
    
    # Tiered Fault Classification (RECALIBRATED parameters - Phase 3)
    # Target: Selective fault refinement contributing to 20-30% total coverage
    fault_tiers:
      major:
        faults: ["Fault_A", "Fault_C", "Fault_D"]               # Three truly sealing faults (restored Fault_D for 20% minimum)
        buffer: 125.0                   # ft - FINE-TUNED: reduced from 150 ft but includes 3rd fault
        factor: 2                       # 2x2 subdivision (reduced from 3x3)
        refined_cell_size_x: 25.0       # ft (moderate cells E-W)
        refined_cell_size_y: 25.0       # ft (moderate cells N-S)
        priority: 1
        
      minor:
        faults: ["Fault_B", "Fault_E"]                          # Lower sealing capacity faults (Fault_D promoted to major)
        buffer: 100.0                   # ft - RECALIBRATED: reduced from 150 ft (33% reduction)
        factor: 1.5                     # 1.5x1.5 subdivision (reduced from 2x2)
        refined_cell_size_x: 35.0       # ft (coarser cells E-W)
        refined_cell_size_y: 35.0       # ft (coarser cells N-S)
        priority: 2
    
    # Legacy uniform refinement (used when tiered_strategy.enable = false)
    buffer: 300.0                     # ft buffer around faults
    factor: 2                        # refinement factor (2x2 subdivision)
    refined_cell_size_x: 25.0        # ft (refined cell E-W)
    refined_cell_size_y: 25.0        # ft (refined cell N-S)
    refined_layer_thickness: 4.0     # ft (refined vertical)
    major_faults_only: true
    
  # High Permeability Streak Refinement
  streak_refinement:
    enable: false                     # Optional refinement
    permeability_threshold: 500.0    # mD threshold
    refined_cell_size: 15.0          # ft
  
  # Grid Refinement Strategy Control
  refinement_control:
    target_coverage_percent: 25.0    # Target refined cell coverage percentage
    coverage_tolerance: 5.0          # ±5% acceptable deviation from target
    load_well_tiers_from: "wells_config.yaml"  # CANONICAL SOURCE for well classifications
    load_fault_tiers_from: "fault_config.yaml" # CANONICAL SOURCE for fault classifications
    optimization_notes:
      - "CANON-FIRST: Well classifications loaded from wells_config.yaml"
      - "CANON-FIRST: Fault classifications loaded from fault_config.yaml"  
      - "Grid refinement parameters distributed to appropriate config files"
      - "No duplication of domain-specific information in grid config"

# PEBI Grid Configuration (NEW - for s05_create_pebi_grid.m)
pebi_grid:
  enable: true                             # Enable PEBI grid generation
  grid_type: "fault_conforming"            # Type: fault_conforming, well_optimized, hybrid
  
  # Domain Definition
  domain_bounds:
    x_min: 0.0                             # ft (Western boundary)
    x_max: 3280.0                          # ft (Eastern boundary) 
    y_min: 0.0                             # ft (Southern boundary)
    y_max: 2950.0                          # ft (Northern boundary)
  
  # Background Grid Size
  background_cell_size: 150.0              # ft (far-field cell size)
  
  # Well Size-Field Configuration loaded from wells_config.yaml
  # CANONICAL SOURCE: wells_config.yaml -> grid_refinement.well_tiers
  # PEBI grid generation loads well parameters from wells config
  
  # Fault Size-Field Configuration (Tiered Approach)  
  fault_zones:
    major:
      faults: ["Fault_A", "Fault_C", "Fault_D"]
      cell_size: 25.0                      # ft (fine resolution for sealing faults)
      buffer_distance: 130.0               # ft (±buffer around fault)
      anisotropy_ratio: 2.0                # along:across fault ratio
      priority: 1                          # Highest priority
      
    minor:
      faults: ["Fault_B", "Fault_E"]  
      cell_size: 40.0                      # ft (standard resolution)
      buffer_distance: 100.0               # ft (±buffer around fault)
      anisotropy_ratio: 2.0                # along:across fault ratio
      priority: 2                          # Medium priority
  
  # Size-Field Blending Parameters
  size_blending:
    method: "minimum"                      # How to combine size fields: minimum, weighted, max
    smooth_transitions: true               # Enable smooth size transitions
    max_size_gradient: 1.3                 # Maximum size change between neighbors
  
  # Geometry Parameters (Anti-hardcoding policy compliance)
  geometry_parameters:
    fault_alignment_tolerance: 50.0        # ft - Tolerance for face alignment with fault
    min_distance_fraction: 0.5             # Minimum distance fraction for point spacing
    well_refinement_fraction: 0.6          # Well refinement fraction for spacing
    boundary_spacing_fraction: 0.8         # Boundary spacing fraction
    depth_validation_tolerance: 50.0       # ft - Tolerance for depth validation
    
  # Grid Quality Control
  quality_control:
    min_angle: 25.0                        # degrees (minimum polygon angle)
    max_aspect_ratio: 4.0                  # Maximum cell aspect ratio in refined areas
    target_cell_count: 9660                # Approximate target cell count (PEBI optimized)
    max_cell_count: 12000                   # Maximum allowed cell count
  
  # UPR Module Parameters
  upr_settings:
    CCFactor_multiplier: 1.0               # Well constraint cell size multiplier
    FCFactor_multiplier: 1.0               # Fault constraint cell size multiplier
    mlqt_max_level: 0                      # Multi-level quadtree refinement levels
    
grid:
  # Basic Grid Dimensions (CANON from 01_Structural_Geology.md Section 3.1)
  nx: 41                               # I-direction cells
  ny: 41                               # J-direction cells  
  nz: 12                               # K-direction cells (layers)
  
  # Cell Sizes (CANON)
  cell_size_x: 80.0                    # ft (E-W direction)
  cell_size_y: 72.0                    # ft (N-S direction)
  
  # Layer Thicknesses (CANON - 12 layers, total 340 ft Eagle West)
  layer_thicknesses: [28.3, 28.3, 28.3, 28.3, 28.3, 28.3, 28.3, 28.3, 28.3, 28.3, 28.3, 28.4]  # ft per layer
  
  # Field Extent (CANON from 01_Structural_Geology.md)
  field_extent_x: 3280.0               # ft (E-W total field extent)
  field_extent_y: 2950.0               # ft (N-S total field extent)
  total_thickness: 340.0               # ft (Eagle West canonical reservoir thickness: 8240-7900 TVDSS)
  thickness_tolerance: 10.0            # ft (validation tolerance for thickness)
  
  # Grid Origin and Orientation (CANON)
  origin_utm_x: 745280.0               # UTM Zone 15N Easting (m)
  origin_utm_y: 3258470.0              # UTM Zone 15N Northing (m)
  grid_orientation: 15.0               # degrees N15°E (aligned with fault trend)
  
  # Depth Reference (CANON)
  datum_depth_tvdss: 8000.0            # ft TVDSS (pressure datum)
  top_structure_tvdss: 7900.0          # ft TVDSS (structural crest)
  base_structure_tvdss: 8240.0         # ft TVDSS (spill point)
  
  # Grid Quality Control
  total_cells: 20172                   # Total grid cells (41×41×12)
  target_active_cells: 9660            # Expected active cells (PEBI optimized)
  max_aspect_ratio: 10.0               # Maximum cell aspect ratio
  
  # Grid Quality Parameters
      
  # Grid Validation Parameters
  validation:
    min_cell_volume: 1000.0            # ft³ minimum cell volume
    max_cell_volume: 100000.0          # ft³ maximum cell volume
    min_layer_thickness: 2.0           # ft minimum layer thickness
    max_layer_thickness: 20.0          # ft maximum layer thickness
    check_orthogonality: true
    orthogonality_tolerance: 0.1       # radians
    
  # MRST Grid Implementation
  mrst_grid:
    grid_type: "cartesian_tensor"      # MRST grid type
    geometry_compute: "automatic"      # Automatic geometry computation
    fault_processing: "explicit"       # Explicit fault representation
    boundary_conditions: "no_flow"     # Default boundary conditions
    grid_coarsening: false             # No initial coarsening
    
  # Physical Constants
  physical:
    gravity_vector: [0, 0, 9.81]       # m/s² (standard gravity)
    reference_pressure: 101325.0       # Pa (1 atm reference)
    reference_temperature: 288.15      # K (15°C reference)