# Grid Configuration for Eagle West Field MRST Simulation
# Simplified format for Python-MRST workflow
# Date: January 30, 2025

grid:
  # Basic grid dimensions (40x40x12 per documentation)
  nx: 40
  ny: 40
  nz: 12
  
  # Cell sizes (per MRST_Implementation.md)
  cell_size_x: 82.0  # ft
  cell_size_y: 74.0  # ft
  
  # Layer thicknesses (12 layers, 8.3 ft each per documentation)
  layer_thicknesses: [8.3, 8.3, 8.3, 8.3, 8.3, 8.3, 8.3, 8.3, 8.3, 8.3, 8.3, 8.3]
  
  # Grid origin
  origin_x: 0.0
  origin_y: 0.0
  origin_z: 8000.0  # ft TVDSS