# Grid Configuration for Eagle West Field MRST Simulation
# Source: 00_Overview.md, 01_Structural_Geology.md (CANON)
# Compatible with s02_create_grid.m and s06_grid_refinement.m requirements
# Date: 2025-08-07
# OPTIMIZED: 2025-08-14 - Phase 3 Implementation with optimized refinement parameters
#
# OPTIMIZATION SUMMARY - PHASE 3 RECALIBRATION:
# - Target Coverage: 20-30% (RECALIBRATED from 82.1% actual)
# - Well Radii: Further reduced by 40-50% (Critical: 250→150, Standard: 175→100, Marginal: removed)
# - Fault Buffers: Further reduced by 45-50% (Major: 275→150, Minor: 150→100 ft)
# - Refinement Factors: Reduced (Critical: 3x3→2x2, Standard: 2x2→1.5x1.5, Marginal: removed)
# - Expected Performance: ~85% reduction in refined cells from current 82.1% to target 25%
# - Validation: Maintains critical feature resolution while achieving computational efficiency

# Refinement Configuration (Top-level for s06_grid_refinement.m)
refinement:
  # Tiered Refinement Strategy - Phase 2 Implementation
  tiered_strategy:
    enable: true
    apply_tier_based_refinement: true
    
  # Well Area Refinement (OPTIMIZED for 25% coverage target)
  well_refinement:
    enable: true
    
    # Tiered Well Classification (RECALIBRATED parameters - Phase 3)
    # Target: 20-30% refined cell coverage (RECALIBRATED from 82.1% actual)
    well_tiers:
      critical:
        wells: ["EW-001", "EW-003", "EW-005", "EW-007", "EW-010"]  # High-rate, multi-lateral, horizontal producers
        radius: 185.0                   # ft - FINAL TUNING: increased to 185 ft to achieve 20% minimum
        factor: 2                       # 2x2 subdivision (reduced from 3x3)
        refined_cell_size_x: 20.0       # ft (standard cells E-W)
        refined_cell_size_y: 18.0       # ft (standard cells N-S)
        priority: 1
        
      standard:
        wells: ["EW-002", "EW-008", "IW-001", "IW-003"]           # Standard producers + key injectors
        radius: 125.0                   # ft - FINE-TUNED: increased from 100 ft to reach 20% minimum
        factor: 1.5                     # 1.5x1.5 subdivision (reduced from 2x2)
        refined_cell_size_x: 25.0       # ft (moderate cells E-W)
        refined_cell_size_y: 22.0       # ft (moderate cells N-S)
        priority: 2
        
      marginal:
        wells: ["EW-004", "EW-006", "EW-009", "IW-002", "IW-004", "IW-005"]  # REMOVED - no refinement
        radius: 0.0                     # ft - RECALIBRATED: removed refinement entirely
        factor: 1                       # No subdivision (no refinement)
        refined_cell_size_x: 0.0        # ft (no refinement)
        refined_cell_size_y: 0.0        # ft (no refinement)
        priority: 0                     # Disabled
    
    # Legacy uniform refinement (used when tiered_strategy.enable = false)
    radius: 250.0                    # ft radius around wellbores
    factor: 2                        # refinement factor (2x2 subdivision)
    refined_cell_size_x: 20.0        # ft (refined cell E-W)
    refined_cell_size_y: 18.0        # ft (refined cell N-S)  
    refined_layer_thickness: 4.0     # ft (refined vertical)
    transition_smooth: true
    
  # Fault Area Refinement (OPTIMIZED for 25% coverage target)
  fault_refinement:
    enable: true
    
    # Tiered Fault Classification (RECALIBRATED parameters - Phase 3)
    # Target: Selective fault refinement contributing to 20-30% total coverage
    fault_tiers:
      major:
        faults: ["Fault_A", "Fault_C", "Fault_D"]               # Three truly sealing faults (restored Fault_D for 20% minimum)
        buffer: 125.0                   # ft - FINE-TUNED: reduced from 150 ft but includes 3rd fault
        factor: 2                       # 2x2 subdivision (reduced from 3x3)
        refined_cell_size_x: 25.0       # ft (moderate cells E-W)
        refined_cell_size_y: 25.0       # ft (moderate cells N-S)
        priority: 1
        
      minor:
        faults: ["Fault_B", "Fault_E"]                          # Lower sealing capacity faults (Fault_D promoted to major)
        buffer: 100.0                   # ft - RECALIBRATED: reduced from 150 ft (33% reduction)
        factor: 1.5                     # 1.5x1.5 subdivision (reduced from 2x2)
        refined_cell_size_x: 35.0       # ft (coarser cells E-W)
        refined_cell_size_y: 35.0       # ft (coarser cells N-S)
        priority: 2
    
    # Legacy uniform refinement (used when tiered_strategy.enable = false)
    buffer: 300.0                     # ft buffer around faults
    factor: 2                        # refinement factor (2x2 subdivision)
    refined_cell_size_x: 25.0        # ft (refined cell E-W)
    refined_cell_size_y: 25.0        # ft (refined cell N-S)
    refined_layer_thickness: 4.0     # ft (refined vertical)
    major_faults_only: true
    
  # High Permeability Streak Refinement
  streak_refinement:
    enable: false                     # Optional refinement
    permeability_threshold: 500.0    # mD threshold
    refined_cell_size: 15.0          # ft
  
  # Optimization Validation (Phase 3 - Recalibrated)
  optimization:
    target_coverage_percent: 25.0    # Target refined cell coverage percentage
    previous_coverage_percent: 82.1  # Actual coverage from Phase 2 testing
    coverage_tolerance: 5.0          # ±5% acceptable deviation from target
    recalibration_notes:
      - "PHASE 3: Aggressive recalibration from 82.1% to target 20-30%"
      - "Critical wells: 3x3→2x2 refinement, radius 250→185 ft (5 wells)"
      - "Standard wells: 2x2→1.5x1.5 refinement, radius 175→125 ft (4 wells)" 
      - "Marginal wells: Removed refinement entirely (6 wells)"
      - "Major faults: 3x3→2x2 refinement, buffer 275→125 ft (3 faults: A,C,D)"
      - "Minor faults: 2x2→1.5x1.5 refinement, buffer 150→100 ft (2 faults: B,E)"
    validation_checkpoints:
      - "Well critical features maintain >2 cell radius minimum"
      - "Fault representation focused on high-sealing capacity boundaries"
      - "Computational efficiency improves by >70% vs. 82.1% coverage"
      - "Total refined cells <6,000 (vs. previous ~16,600 at 82.1%)"
    optimization_reference: "Grid refinement recalibration analysis 2025-08-14"

grid:
  # Basic Grid Dimensions (CANON from 01_Structural_Geology.md Section 3.1)
  nx: 41                               # I-direction cells
  ny: 41                               # J-direction cells  
  nz: 12                               # K-direction cells (layers)
  
  # Cell Sizes (CANON)
  cell_size_x: 82.0                    # ft (E-W direction)
  cell_size_y: 74.0                    # ft (N-S direction)
  
  # Layer Thicknesses (CANON - 12 layers, total 100 ft)
  layer_thicknesses: [8.3, 8.3, 8.3, 8.3, 8.3, 8.3, 8.3, 8.3, 8.3, 8.3, 8.3, 8.7]  # ft per layer
  
  # Field Extent (CANON from 01_Structural_Geology.md)
  field_extent_x: 3280.0               # ft (E-W total field extent)
  field_extent_y: 2950.0               # ft (N-S total field extent)
  total_thickness: 100.0               # ft (total reservoir thickness)
  
  # Grid Origin and Orientation (CANON)
  origin_utm_x: 745280.0               # UTM Zone 15N Easting (m)
  origin_utm_y: 3258470.0              # UTM Zone 15N Northing (m)
  grid_orientation: 15.0               # degrees N15°E (aligned with fault trend)
  
  # Depth Reference (CANON)
  datum_depth_tvdss: 8000.0            # ft TVDSS (pressure datum)
  top_structure_tvdss: 7900.0          # ft TVDSS (structural crest)
  base_structure_tvdss: 8240.0         # ft TVDSS (spill point)
  
  # Grid Quality Control
  total_cells: 20172                   # Total grid cells (41×41×12)
  target_active_cells: 19000           # Expected active cells
  max_aspect_ratio: 10.0               # Maximum cell aspect ratio
  
  # Grid Quality Parameters
      
  # Grid Validation Parameters
  validation:
    min_cell_volume: 1000.0            # ft³ minimum cell volume
    max_cell_volume: 100000.0          # ft³ maximum cell volume
    min_layer_thickness: 2.0           # ft minimum layer thickness
    max_layer_thickness: 20.0          # ft maximum layer thickness
    check_orthogonality: true
    orthogonality_tolerance: 0.1       # radians
    
  # MRST Grid Implementation
  mrst_grid:
    grid_type: "cartesian_tensor"      # MRST grid type
    geometry_compute: "automatic"      # Automatic geometry computation
    fault_processing: "explicit"       # Explicit fault representation
    boundary_conditions: "no_flow"     # Default boundary conditions
    grid_coarsening: false             # No initial coarsening
    
  # Physical Constants
  physical:
    gravity_vector: [0, 0, 9.81]       # m/s² (standard gravity)
    reference_pressure: 101325.0       # Pa (1 atm reference)
    reference_temperature: 288.15      # K (15°C reference)