# Initial Conditions Configuration for MRST Reservoir Simulation
# Eagle West Field - 15-Well Development Program
#
# Based on: /workspace/obsidian-vault/Planning/Reservoir_Definition/07_Initialization.md
# Created: 2025-07-31
# Purpose: Pressure and saturation initialization for 3-phase simulation

# PRESSURE INITIALIZATION
pressure_initialization:
  # REFERENCE CONDITIONS
  reference_pressure: 2900    # psi - At datum depth
  reference_depth: 8000       # ft TVDSS - Datum depth
  pressure_gradient: 0.433    # psi/ft - Hydrostatic gradient
  
  # PRESSURE CALCULATION METHOD
  initialization_method: "hydrostatic_equilibrium"
  equilibrium_tolerance: 0.1  # psi - Equilibrium tolerance
  
  # DEPTH-PRESSURE RELATIONSHIP
  pressure_vs_depth:
    top_reservoir: 7881       # ft TVDSS - Top depth
    pressure_at_top: 2848.5   # psi - Calculated pressure at top
    base_reservoir: 8119      # ft TVDSS - Base depth  
    pressure_at_base: 2951.2  # psi - Calculated pressure at base
    
  # COMPARTMENT PRESSURES (if applicable)
  pressure_compartments:
    northern_block:
      reference_pressure: 2900 # psi
      pressure_gradient: 0.433 # psi/ft
    southern_block:
      reference_pressure: 2895 # psi - Slightly lower
      pressure_gradient: 0.433 # psi/ft

# FLUID CONTACTS AND INTERFACES
fluid_contacts:
  # PRIMARY CONTACTS
  oil_water_contact: 8150     # ft TVDSS - Sharp OWC
  gas_oil_contact: null       # No initial GOC (undersaturated)
  
  # CONTACT PROPERTIES
  owc_properties:
    contact_type: "sharp"     # Sharp vs. transitional
    transition_zone: 50       # ft - Capillary transition zone
    contact_uncertainty: 5    # ft - Contact depth uncertainty
  
  # CAPILLARY PRESSURE AT CONTACTS
  capillary_pressure_owc:
    entry_pressure: 2.0       # psi - Oil entry pressure
    height_above_fwl: 269     # ft - Oil column height
    max_height: 300           # ft - Maximum oil column

# INITIAL SATURATION DISTRIBUTION
saturation_initialization:
  # SATURATION FUNCTIONS
  saturation_method: "capillary_pressure"
  
  # ABOVE OIL-WATER CONTACT
  above_owc:
    oil_saturation: 0.75      # Initial oil saturation
    water_saturation: 0.25    # Connate water saturation
    gas_saturation: 0.00      # No free gas initially
    
    # SATURATION VS HEIGHT
    saturation_height_function:
      method: "leverett_j_function"
      j_function_parameters:
        sigma_ow: 25            # dyne/cm - Oil-water IFT
        contact_angle: 0        # degrees - Wetting angle
        porosity_reference: 0.225 # Reference porosity
        permeability_reference: 160 # mD - Reference permeability
  
  # BELOW OIL-WATER CONTACT  
  below_owc:
    oil_saturation: 0.00      # No oil below OWC
    water_saturation: 1.00    # 100% water below OWC
    gas_saturation: 0.00      # No gas below OWC
  
  # TRANSITION ZONE MODELING
  transition_zone:
    enable_transition: true
    zone_thickness: 50        # ft
    saturation_profile: "capillary_pressure"
    
    # TRANSITION PARAMETERS
    transition_parameters:
      lambda: 2.5             # Pore size distribution
      entry_pressure: 2.0     # psi
      irreducible_water: 0.20 # Swir
      residual_oil: 0.25      # Sor

# PRESSURE-VOLUME-TEMPERATURE INITIALIZATION
pvt_initialization:
  # RESERVOIR TEMPERATURE
  reservoir_temperature: 176  # °F - Constant temperature
  temperature_gradient: 0.0   # °F/ft - Isothermal reservoir
  
  # INITIAL FLUID STATES
  initial_bubble_point: 2100  # psi - Bubble point pressure
  initial_dew_point: null     # No dew point (oil reservoir)
  
  # GAS-OIL RATIO INITIALIZATION
  initial_gor_distribution:
    above_bubble_point: 450   # scf/STB - Solution GOR
    at_bubble_point: 450      # scf/STB - Maximum solution GOR
    below_bubble_point: 450   # scf/STB - Constant solution GOR
  
  # PHASE STATE VALIDATION
  phase_state_check:
    undersaturated_oil: true  # Initially undersaturated
    free_gas_check: false     # No free gas initially
    critical_point_check: true # Validate critical conditions

# ROCK-FLUID INTERACTION INITIALIZATION
rock_fluid_initialization:
  # WETTABILITY
  wettability_state: "water_wet"  # Reservoir wettability
  wettability_index: 0.2     # Amott-Harvey index
  
  # INTERFACIAL TENSIONS
  interfacial_tensions:
    oil_water_ift: 25.0       # dyne/cm at reservoir conditions
    gas_oil_ift: 5.0          # dyne/cm at reservoir conditions
    temperature_dependence: true
  
  # CONTACT ANGLES
  contact_angles:
    oil_water_rock: 20        # degrees - Water-wet surface
    gas_oil_rock: 0           # degrees - Neutral wetting

# AQUIFER INITIALIZATION
aquifer_initialization:
  # AQUIFER SUPPORT
  aquifer_present: true
  aquifer_type: "infinite_acting"
  
  # AQUIFER PROPERTIES
  aquifer_properties:
    aquifer_strength: 1.0e6   # RB/psi - Aquifer constant
    aquifer_radius: 10000     # ft - Effective aquifer radius
    aquifer_porosity: 0.15    # Aquifer porosity
    aquifer_compressibility: 3.0e-6 # 1/psi
    aquifer_permeability: 50  # mD - Aquifer permeability
    aquifer_thickness: 50     # ft - Aquifer thickness
  
  # AQUIFER CONNECTIVITY
  aquifer_connections:
    connection_type: "bottom"  # Bottom aquifer connection
    connection_area: 2600     # acres - Connection area
    productivity_index: 100   # STB/day/psi - Aquifer PI

# INITIALIZATION QUALITY CONTROL
quality_control:
  # MASS BALANCE CHECKS
  mass_balance:
    oil_mass_tolerance: 0.01  # 1% tolerance
    water_mass_tolerance: 0.01 # 1% tolerance
    gas_mass_tolerance: 0.01  # 1% tolerance
  
  # PRESSURE EQUILIBRIUM
  pressure_equilibrium:
    hydrostatic_tolerance: 0.5 # psi tolerance
    contact_pressure_check: true
    compartment_balance_check: true
  
  # SATURATION VALIDATION
  saturation_validation:
    saturation_sum_tolerance: 0.001 # Sum must equal 1.0
    minimum_saturation: 0.0   # Minimum allowable saturation
    maximum_saturation: 1.0   # Maximum allowable saturation
    
  # PHYSICAL CONSISTENCY
  physical_consistency:
    bubble_point_check: true  # Validate bubble point
    phase_behavior_check: true # Check phase transitions
    capillary_pressure_check: true # Validate Pc curves

# SIMULATION TIMESTEP INITIALIZATION
timestep_initialization:
  # INITIAL TIMESTEP
  initial_timestep: 1.0       # days - First timestep
  minimum_timestep: 0.01      # days - Minimum allowed
  maximum_timestep: 30        # days - Maximum allowed
  
  # TIMESTEP CONTROL
  timestep_control:
    pressure_change_limit: 50 # psi - Max pressure change per step
    saturation_change_limit: 0.05 # Max saturation change per step
    rate_change_limit: 0.1    # Max rate change fraction
  
  # RAMP-UP SCHEDULE
  ramp_up_schedule:
    enable_ramp_up: true
    ramp_duration: 30         # days
    initial_rate_fraction: 0.1 # Start at 10% of target rate

# NUMERICAL INITIALIZATION PARAMETERS
numerical_parameters:
  # NEWTON SOLVER SETTINGS
  newton_tolerance: 1.0e-6    # Newton iteration tolerance
  maximum_newton_iterations: 10
  minimum_newton_iterations: 1
  
  # LINEAR SOLVER SETTINGS
  linear_solver: "direct"     # Direct or iterative
  linear_tolerance: 1.0e-8    # Linear solver tolerance
  
  # INITIALIZATION SOLVER
  initialization_solver:
    method: "gravity_segregation" # Initialization method
    iterations: 50            # Maximum iterations
    tolerance: 1.0e-6         # Convergence tolerance

# UNCERTAINTY QUANTIFICATION
uncertainty_parameters:
  # PRESSURE UNCERTAINTY
  pressure_uncertainty:
    datum_pressure_std: 25    # psi - Standard deviation
    gradient_uncertainty: 0.01 # psi/ft - Gradient uncertainty
  
  # CONTACT UNCERTAINTY
  contact_uncertainty:
    owc_depth_std: 5          # ft - OWC depth uncertainty
    transition_zone_std: 10   # ft - Transition zone uncertainty
  
  # SATURATION UNCERTAINTY
  saturation_uncertainty:
    connate_water_std: 0.02   # Swc uncertainty
    oil_saturation_std: 0.03  # So uncertainty above OWC

# MRST IMPLEMENTATION PARAMETERS
mrst_implementation:
  # INITIALIZATION METHOD
  initialization_function: "initResSol"
  equilibrium_method: "gravity"
  pressure_method: "hydrostatic"
  
  # STATE OBJECT INITIALIZATION
  state_variables:
    - "pressure"              # Cell pressures
    - "s"                     # Phase saturations
    - "rs"                    # Solution gas-oil ratio
    - "rv"                    # Vaporized oil-gas ratio (if applicable)
  
  # REGION SUPPORT
  regions:
    pvt_regions: 1            # Number of PVT regions
    saturation_regions: 1     # Number of saturation regions
    fip_regions: 2            # Number of FIP regions (compartments)

# VALIDATION AND DEBUGGING
validation_parameters:
  # OUTPUT CONTROLS
  output_initial_state: true  # Output initialization results
  plot_initialization: true  # Create initialization plots
  save_initialization: true  # Save initialization data
  
  # DIAGNOSTIC OUTPUT
  diagnostic_output:
    pressure_maps: true       # Output pressure distribution
    saturation_maps: true     # Output saturation distribution
    contact_validation: true  # Validate fluid contacts
    material_balance: true    # Check material balance

# COMMENTS AND METADATA
comments:
  - "Initial conditions for Eagle West Field 15-well development"
  - "Hydrostatic equilibrium with 2900 psi at 8000 ft datum"
  - "Sharp oil-water contact at 8150 ft TVDSS"
  - "Initially undersaturated oil with 450 scf/STB solution GOR"
  - "50 ft capillary transition zone above OWC"
  - "Bottom aquifer support for pressure maintenance"
  - "Two pressure compartments: Northern and Southern blocks"