# Rock Properties Configuration for MRST Reservoir Simulation
# Eagle West Field - 15-Well Development Program
#
# Based on: /workspace/obsidian-vault/Planning/Reservoir_Definition/02_Rock_Properties.md
# Created: 2025-07-31
# Purpose: Rock properties, porosity, permeability for MRST simulation

# PRIMARY LITHOLOGY - SANDSTONE RESERVOIR
sandstone_properties:
  lithology_type: "sandstone"
  
  # POROSITY DISTRIBUTION
  porosity:
    average: 0.225            # 22.5% - Average porosity
    minimum: 0.20             # 20% - Minimum porosity
    maximum: 0.25             # 25% - Maximum porosity
    distribution: "lognormal" # Statistical distribution
    standard_deviation: 0.02  # Porosity variability
  
  # PERMEABILITY DISTRIBUTION
  horizontal_permeability:
    average: 160              # mD - Average horizontal permeability
    minimum: 120              # mD - Minimum horizontal permeability
    maximum: 200              # mD - Maximum horizontal permeability
    distribution: "lognormal" # Statistical distribution
    correlation_length_x: 500 # ft - Correlation in X direction
    correlation_length_y: 500 # ft - Correlation in Y direction
  
  vertical_permeability:
    kv_kh_ratio_avg: 0.20     # Average Kv/Kh ratio
    kv_kh_ratio_min: 0.15     # Minimum Kv/Kh ratio
    kv_kh_ratio_max: 0.25     # Maximum Kv/Kh ratio
  
  # COMPRESSIBILITY
  rock_compressibility: 3.0e-6  # 1/psi - Rock compressibility
  
  # THERMAL PROPERTIES
  thermal_conductivity: 1.5     # BTU/hr-ft-°F
  heat_capacity: 0.2           # BTU/lbm-°F

# SECONDARY LITHOLOGIES
shale_properties:
  lithology_type: "shale"
  
  # SEAL/BARRIER PROPERTIES
  porosity:
    average: 0.08             # 8% - Low porosity
    minimum: 0.05             # 5% - Minimum porosity
    maximum: 0.12             # 12% - Maximum porosity
  
  horizontal_permeability:
    average: 0.01             # mD - Very low permeability
    minimum: 0.001            # mD - Minimum permeability
    maximum: 0.1              # mD - Maximum permeability
  
  vertical_permeability:
    kv_kh_ratio_avg: 0.1      # Lower vertical flow
  
  rock_compressibility: 5.0e-6  # 1/psi - Higher compressibility

limestone_properties:
  lithology_type: "limestone"
  
  # TIGHT CARBONATE PROPERTIES
  porosity:
    average: 0.15             # 15% - Moderate porosity
    minimum: 0.10             # 10% - Minimum porosity
    maximum: 0.20             # 20% - Maximum porosity
  
  horizontal_permeability:
    average: 50               # mD - Moderate permeability
    minimum: 10               # mD - Minimum permeability
    maximum: 100              # mD - Maximum permeability
  
  vertical_permeability:
    kv_kh_ratio_avg: 0.15     # Reduced vertical flow
  
  rock_compressibility: 2.0e-6  # 1/psi - Lower compressibility

# LAYER ARCHITECTURE AND FACIES
layer_definition:
  total_layers: 10            # Number of K layers (CORRECTED from 12)
  
  # LAYER PROPERTIES BY K-INDEX
  layer_properties:
    - k_index: 1
      thickness: 7.25         # ft (CORRECTED for 10-layer grid)
      lithology: "sandstone"
      net_to_gross: 0.8
      quality: "excellent"
    
    - k_index: 2
      thickness: 7.25         # ft (CORRECTED for 10-layer grid)
      lithology: "sandstone"
      net_to_gross: 0.7
      quality: "good"
    
    - k_index: 3
      thickness: 7.25         # ft (CORRECTED for 10-layer grid)
      lithology: "shale"
      net_to_gross: 0.1
      quality: "barrier"
    
    - k_index: 4
      thickness: 7.25         # ft (CORRECTED for 10-layer grid)
      lithology: "sandstone"
      net_to_gross: 0.75
      quality: "excellent"
    
    - k_index: 5
      thickness: 7.25         # ft (CORRECTED for 10-layer grid)
      lithology: "sandstone"
      net_to_gross: 0.6
      quality: "good"
    
    - k_index: 6
      thickness: 7.25         # ft (CORRECTED for 10-layer grid)
      lithology: "limestone"
      net_to_gross: 0.4
      quality: "fair"
    
    - k_index: 7
      thickness: 7.25         # ft (CORRECTED for 10-layer grid)
      lithology: "sandstone"
      net_to_gross: 0.8
      quality: "excellent"
    
    - k_index: 8
      thickness: 7.25         # ft (CORRECTED for 10-layer grid)
      lithology: "sandstone"
      net_to_gross: 0.65
      quality: "good"
    
    - k_index: 9
      thickness: 7.25         # ft (CORRECTED for 10-layer grid)
      lithology: "shale"
      net_to_gross: 0.05
      quality: "seal"
    
    - k_index: 10
      thickness: 7.25         # ft (CORRECTED for 10-layer grid)
      lithology: "sandstone"
      net_to_gross: 0.7
      quality: "good"

# HETEROGENEITY MODELING
heterogeneity_parameters:
  # POROSITY-PERMEABILITY CORRELATION
  phi_k_correlation:
    correlation_type: "kozeny_carman"
    exponent: 3.0             # Kozeny-Carman exponent
    tortuosity: 2.0           # Tortuosity factor
  
  # SPATIAL CORRELATION
  variogram_parameters:
    range_major: 1500         # ft - Major correlation range
    range_minor: 800          # ft - Minor correlation range
    azimuth: 45               # degrees - Principal direction
    nugget: 0.1               # Nugget effect
    sill: 1.0                 # Variogram sill

# RELATIVE PERMEABILITY ENDPOINTS
relative_permeability_endpoints:
  # WATER-OIL SYSTEM
  water_oil:
    swc: 0.20                 # Connate water saturation
    sor_w: 0.25               # Residual oil to water
    krw_max: 0.4              # Maximum water rel perm
    kro_max_w: 0.8            # Maximum oil rel perm to water
    nw: 2.0                   # Water Corey exponent
    no_w: 2.5                 # Oil Corey exponent (to water)
  
  # GAS-OIL SYSTEM  
  gas_oil:
    sgc: 0.05                 # Critical gas saturation
    sor_g: 0.20               # Residual oil to gas
    krg_max: 0.8              # Maximum gas rel perm
    kro_max_g: 0.9            # Maximum oil rel perm to gas
    ng: 1.8                   # Gas Corey exponent
    no_g: 2.0                 # Oil Corey exponent (to gas)

# CAPILLARY PRESSURE PARAMETERS
capillary_pressure:
  # WATER-OIL CAPILLARY PRESSURE
  water_oil_pc:
    entry_pressure: 2.0       # psi - Entry pressure
    lambda: 2.5               # Pore size distribution index
    pc_max: 15.0              # psi - Maximum capillary pressure
  
  # GAS-OIL CAPILLARY PRESSURE
  gas_oil_pc:
    entry_pressure: 0.5       # psi - Entry pressure
    lambda: 2.0               # Pore size distribution index
    pc_max: 8.0               # psi - Maximum capillary pressure

# QUALITY CONTROL AND VALIDATION
quality_control:
  porosity_cutoff: 0.10       # Minimum porosity for flow
  permeability_cutoff: 0.1    # mD - Minimum permeability for flow
  net_to_gross_cutoff: 0.1    # Minimum N/G for reservoir quality
  
  # VALIDATION CHECKS
  mass_balance_check: true
  property_correlation_check: true
  layer_continuity_check: true

# MRST IMPLEMENTATION NOTES
mrst_implementation:
  property_assignment: "layer_based"   # Layer-based property assignment
  upscaling_method: "harmonic_mean"    # For permeability upscaling  
  porosity_averaging: "arithmetic"     # For porosity averaging
  heterogeneity_realization: 1        # Realization number

# COMMENTS AND METADATA
comments:
  - "Rock properties for Eagle West Field 15-well development"
  - "Primary lithology: Sandstone with shale/limestone interbeds"
  - "Porosity range: 20-25% (sandstone), 5-12% (shale), 10-20% (limestone)"
  - "Permeability range: 120-200 mD (sandstone), 0.001-0.1 mD (shale)"
  - "Kv/Kh ratio: 0.15-0.25 for vertical flow modeling"
  - "10 layers with variable net-to-gross ratios (CORRECTED)"