# Rock Properties Configuration for Eagle West Field MRST Simulation
# Source: 02_Rock_Properties.md (CANON)
# Compatible with s07_define_rock_types.m requirements
# Date: 2025-08-07

rock_properties:
  # Layer-by-Layer Properties (CANON from 02_Rock_Properties.md)
  # 12 layers representing major flow units and barriers
  
  # Porosity by Layer (fraction)
  porosity_layers: [0.200, 0.195, 0.190, 0.050, 0.235, 0.230, 0.225, 0.050, 0.150, 0.145, 0.140, 0.135]
  
  # Horizontal Permeability by Layer (mD)
  permeability_layers: [90, 85, 80, 0.01, 175, 170, 160, 0.01, 30, 25, 22, 20]
  
  # Vertical-Horizontal Permeability Ratios
  kv_kh_ratios: [0.5, 0.5, 0.5, 0.1, 0.5, 0.5, 0.5, 0.1, 0.5, 0.5, 0.5, 0.5]
  
  # Lithology Classification by Layer
  lithology_layers: ["sandstone", "sandstone", "sandstone", "shale", "sandstone", "sandstone", "sandstone", "shale", "sandstone", "sandstone", "sandstone", "sandstone"]
  
  # Rock Type Classification (CANON from 02_Rock_Properties.md Section 2.1)
  rock_type_definitions:
    RT1_high_perm_sandstone:
      description: "High permeability sandstone"
      porosity_range: [0.25, 0.32]
      permeability_range_md: [300, 850]
      kv_kh_ratio: 0.5
      layers: [5, 6, 7]  # Middle zone high quality
      reservoir_quality_index: 3.5  # μm
      flow_zone_indicator: [8, 15]  # μm range
      
    RT2_medium_perm_sandstone:
      description: "Medium permeability sandstone"
      porosity_range: [0.20, 0.25]
      permeability_range_md: [100, 300]
      kv_kh_ratio: 0.5
      layers: [1, 2, 3]  # Upper zone
      reservoir_quality_index: 2.5  # μm
      flow_zone_indicator: [5, 8]   # μm range
      
    RT3_low_perm_sandstone:
      description: "Low permeability sandstone"
      porosity_range: [0.15, 0.20]
      permeability_range_md: [25, 100]
      kv_kh_ratio: 0.5
      layers: [9, 10, 11, 12]  # Lower zone
      reservoir_quality_index: 1.5  # μm
      flow_zone_indicator: [3, 5]   # μm range
      
    RT4_tight_sandstone:
      description: "Tight cemented sandstone"
      porosity_range: [0.10, 0.15]
      permeability_range_md: [5, 25]
      kv_kh_ratio: 0.25
      layers: []  # Not present in current model
      reservoir_quality_index: 0.8  # μm
      flow_zone_indicator: [1.5, 3] # μm range
      
    RT5_vuggy_limestone:
      description: "Limestone with secondary porosity"
      porosity_range: [0.15, 0.28]
      permeability_range_md: [50, 300]
      kv_kh_ratio: 0.5
      layers: []  # Not present in current model
      reservoir_quality_index: 2.0  # μm
      flow_zone_indicator: [4, 10]  # μm range
      
    RT6_shale_barrier:
      description: "Shale barriers and flow baffles"
      porosity_range: [0.02, 0.08]
      permeability_range_md: [0.001, 0.1]
      kv_kh_ratio: 0.1
      layers: [4, 8]  # Barrier layers
      reservoir_quality_index: 0.1  # μm
      flow_zone_indicator: [0.1, 1.0]  # μm range
      
  # Porosity-Permeability Correlations (CANON from 02_Rock_Properties.md)
  porosity_permeability_correlations:
    RT1_high_perm:
      correlation: "k = 0.0314 * phi^2.1"
      r_squared: 0.82
      applicable_range_porosity: [25, 32]  # %
      
    RT2_medium_perm:
      correlation: "k = 0.0156 * phi^2.5"
      r_squared: 0.78
      applicable_range_porosity: [20, 25]  # %
      
    RT3_low_perm:
      correlation: "k = 0.0089 * phi^3.2"
      r_squared: 0.75
      applicable_range_porosity: [15, 20]  # %
      
    RT6_shale:
      correlation: "k = 0.0001 * phi^6.0"
      r_squared: 0.45
      applicable_range_porosity: [2, 8]    # %
      
  # Layer Architecture and Connectivity (CANON)
  layer_architecture:
    upper_zone:
      layers: [1, 2, 3]
      description: "High quality sandstones"
      avg_net_to_gross: 0.85
      lateral_continuity: [500, 1200]  # m range
      
    shale_barrier_1:
      layers: [4]
      description: "Upper shale barrier"
      thickness_range: [2, 4]  # ft
      lateral_continuity: [800, 2000]  # m
      sealing_capacity: "high"
      
    middle_zone:
      layers: [5, 6, 7]
      description: "Highest quality sandstones"
      avg_net_to_gross: 0.90
      lateral_continuity: [800, 1500]  # m range
      
    shale_barrier_2:
      layers: [8]
      description: "Middle shale barrier"
      thickness_range: [1, 3]  # ft
      lateral_continuity: [600, 1800]  # m
      sealing_capacity: "moderate"
      
    lower_zone:
      layers: [9, 10, 11, 12]
      description: "Medium quality sandstones"
      avg_net_to_gross: 0.70
      lateral_continuity: [400, 1000]  # m range
      
  # Heterogeneity Parameters (for s09_spatial_heterogeneity.m)
  heterogeneity:
    spatial_correlation:
      major_direction_range: 1500.0    # ft (along depositional strike)
      minor_direction_range: 800.0     # ft (perpendicular to strike)
      vertical_range: 15.0             # ft (vertical correlation)
      
    variogram_parameters:
      nugget_effect: 0.05              # Measurement noise
      sill_variance: 0.15              # Total variance
      variogram_type: "exponential"    # Model type
      
    statistical_distributions:
      porosity_distribution: "normal"
      porosity_coefficient_variation: 0.12
      permeability_distribution: "lognormal"
      permeability_coefficient_variation: 0.85
      
  # Rock type classification thresholds (for s07)
  rock_type_classification:
    rt1_high_perm_threshold: 80         # mD - minimum permeability for RT1 (high quality)
    rt2_medium_perm_threshold: 20       # mD - minimum permeability for RT2 (medium quality)
    # Below rt2_threshold = RT6 (barriers/tight)
    
  # Heterogeneity parameters for s09 (spatial variation factors)
  heterogeneity_parameters:
    porosity_variation_factor: 0.05     # ±5% variation factor for porosity
    permeability_variation_factor: 0.1  # ±10% variation factor for permeability
    minimum_porosity: 0.01              # Minimum allowed porosity (1%)
    maximum_porosity: 0.35              # Maximum allowed porosity (35%)
      
  # Rock Compressibility and Geomechanics (CANON)
  geomechanical_properties:
    matrix_compressibility:
      sandstone: 2.1e-6              # 1/psi (grain bulk modulus based)
      shale: 3.5e-6                  # 1/psi (clay minerals based)
      limestone: 1.8e-6              # 1/psi (calcite based)
      
    pore_compressibility:
      reference_pressure: 2000.0     # psi
      RT1_compressibility: 3.5e-6    # 1/psi
      RT2_compressibility: 4.2e-6    # 1/psi
      RT6_compressibility: 12.5e-6   # 1/psi
      
  # Validation and Quality Control
  validation:
    data_source: "Core_analysis_and_logs"
    porosity_measurement_precision: 0.01  # ±1% porosity unit
    permeability_measurement_precision: 0.15  # ±15% relative
    spatial_coverage: "comprehensive"
    quality_flags:
      high_confidence_layers: [1, 2, 3, 5, 6, 7]
      medium_confidence_layers: [9, 10, 11, 12]
      barrier_validation: "pressure_test_confirmed"