# Rock Properties Configuration
# This file contains grid, geological layers, porosity, permeability, and geomechanical properties
# Used by: s01_setup_field.m

# Grid Configuration
grid:
  nx: 20                      # Number of cells in X direction
  ny: 20                      # Number of cells in Y direction
  nz: 10                      # Number of cells in Z direction (3D simulation)
  dx: 164.0                   # Cell size in X direction [ft]
  dy: 164.0                   # Cell size in Y direction [ft]
  dz: [50.0, 40.0, 35.0, 30.0, 25.0, 20.0, 15.0, 10.0, 8.0, 5.0]  # Variable layer thickness [ft]

# General Settings
general:
  random_seed: 42             # Random seed for reproducible results

# Porosity Configuration
porosity:
  base_value: 0.20            # Base porosity [-]
  variation_amplitude: 0.10   # Amplitude of spatial variation [-]
  bounds:
    min: 0.05                 # Minimum allowed porosity [-]
    max: 0.35                 # Maximum allowed porosity [-]
  correlation_length: 656.0    # Spatial correlation length [ft]
  random_amplitude_factor: 0.5 # Factor for random variation [-]

# Permeability Configuration
permeability:
  base_value: 100.0           # Base permeability [mD]
  variation_amplitude: 80.0   # Amplitude of spatial variation [mD]
  bounds:
    min: 10.0                 # Minimum allowed permeability [mD]
    max: 500.0                # Maximum allowed permeability [mD]
  correlation_length: 984.0   # Spatial correlation length [ft]
  porosity_correlation: 0.8   # Correlation with porosity [-]
  tensor:
    Kx_factor: 1.0            # Permeability tensor factor in X direction [-]
    Ky_factor: 1.0            # Permeability tensor factor in Y direction [-]
    Kz_factor: 1.0            # Permeability tensor factor in Z direction [-]

# Rock Properties
rock:
  reference_pressure: 2900.0
  
  # Geological layers (from top to bottom)
  layers:
    - id: 1
      name: "Shale Cap"
      depth_range: [7900, 7950]      # Depth range [top, bottom] [ft]
      thickness: 50.0                # Layer thickness [ft]
      lithology: "shale"
      porosity: 0.08                 # Average porosity [-]
      permeability: 0.1              # Average permeability [mD]
      compressibility: 1.0e-6        # Rock compressibility [1/psi]
      
    - id: 2  
      name: "Reservoir Sand 1"
      depth_range: [7950, 7990]      # Depth range [ft]
      thickness: 40.0                # Layer thickness [ft]
      lithology: "sandstone"
      porosity: 0.25                 # Average porosity [-]
      permeability: 200.0            # Average permeability [mD]
      compressibility: 3.1e-6        # Rock compressibility [1/psi]
      
    - id: 3
      name: "Shale Barrier"
      depth_range: [7990, 8025]      # Depth range [ft]
      thickness: 35.0                # Layer thickness [ft]
      lithology: "shale"
      porosity: 0.10                 # Average porosity [-]
      permeability: 0.5              # Average permeability [mD]
      compressibility: 1.2e-6        # Rock compressibility [1/psi]
      
    - id: 4
      name: "Reservoir Sand 2"
      depth_range: [8025, 8055]      # Depth range [ft]
      thickness: 30.0                # Layer thickness [ft]
      lithology: "sandstone"
      porosity: 0.22                 # Average porosity [-]
      permeability: 150.0            # Average permeability [mD]
      compressibility: 3.5e-6        # Rock compressibility [1/psi]
      
    - id: 5
      name: "Limestone"
      depth_range: [8055, 8080]      # Depth range [ft]
      thickness: 25.0                # Layer thickness [ft]
      lithology: "limestone"
      porosity: 0.18                 # Average porosity [-]
      permeability: 80.0             # Average permeability [mD]
      compressibility: 2.1e-6        # Rock compressibility [1/psi]
      
    - id: 6
      name: "Tight Sand"
      depth_range: [8080, 8100]      # Depth range [ft]
      thickness: 20.0                # Layer thickness [ft]
      lithology: "sandstone"
      porosity: 0.15                 # Average porosity [-]
      permeability: 25.0             # Average permeability [mD]
      compressibility: 2.8e-6        # Rock compressibility [1/psi]
      
    - id: 7
      name: "Reservoir Sand 3"
      depth_range: [8100, 8115]      # Depth range [ft]
      thickness: 15.0                # Layer thickness [ft]
      lithology: "sandstone"
      porosity: 0.20                 # Average porosity [-]
      permeability: 120.0            # Average permeability [mD]
      compressibility: 3.2e-6        # Rock compressibility [1/psi]
      
    - id: 8
      name: "Shale Seal"
      depth_range: [8115, 8125]      # Depth range [ft]
      thickness: 10.0                # Layer thickness [ft]
      lithology: "shale"
      porosity: 0.06                 # Average porosity [-]
      permeability: 0.05             # Average permeability [mD]
      compressibility: 1.0e-6        # Rock compressibility [1/psi]
      
    - id: 9
      name: "Aquifer Sand"
      depth_range: [8125, 8133]      # Depth range [ft]
      thickness: 8.0                 # Layer thickness [ft]
      lithology: "sandstone"
      porosity: 0.28                 # Average porosity [-]
      permeability: 300.0            # Average permeability [mD]
      compressibility: 4.0e-6        # Rock compressibility [1/psi]
      
    - id: 10
      name: "Basement"
      depth_range: [8133, 8138]      # Depth range [ft]
      thickness: 5.0                 # Layer thickness [ft]
      lithology: "granite"
      porosity: 0.02                 # Average porosity [-]
      permeability: 0.001            # Average permeability [mD]
      compressibility: 0.5e-6        # Rock compressibility [1/psi]

# Geomechanical Properties
geomechanics:
  enabled: true                 # Enable geomechanical coupling
  plasticity: false             # Enable plasticity (false: no)
  
  # Stress parameters
  stress:
    surface_stress: 2000.0       # Surface total stress [psi]
    overburden_gradient: 1.0     # Overburden gradient [psi/ft]
    pore_pressure_gradient: 0.433  # Pore pressure gradient [psi/ft]
    min_horizontal_stress_ratio: 0.7  # K0 ratio [-]
    max_horizontal_stress_ratio: 1.2  # K1 ratio [-]
    min_effective_stress: 100.0      # Minimum effective stress [psi]
    
  # Mechanical properties
  mechanical:
    young_modulus: 1450000.0      # Young's modulus [psi]
    poisson_ratio: 0.25           # Poisson's ratio [-]
    biot_coefficient: 0.8         # Biot coefficient [-]