# Rock Properties Configuration for Eagle West Field MRST Simulation
# Simplified format for Python-MRST workflow
# Date: January 30, 2025

rock_properties:
  # Layer-by-layer properties for 12 layers (realistic distribution)
  # Based on: 02_Rock_Properties.md + 08_MRST_Implementation.md
  # Upper Zone (Layers 1-3: Sand, Layer 4: Shale barrier)
  # Middle Zone (Layers 5-7: Sand, Layer 8: Shale barrier)  
  # Lower Zone (Layers 9-12: Sand with decreasing quality)
  
  porosity_layers: [0.200, 0.195, 0.190, 0.050, 0.235, 0.230, 0.225, 0.050, 0.150, 0.145, 0.140, 0.135]
  
  permeability_layers: [90, 85, 80, 0.01, 175, 170, 160, 0.01, 30, 25, 22, 20]
  
  # Vertical-horizontal permeability ratios by layer
  kv_kh_ratios: [0.5, 0.5, 0.5, 0.1, 0.5, 0.5, 0.5, 0.1, 0.5, 0.5, 0.5, 0.5]
  
  # Lithology by layer (for reference)
  lithology_layers: ["sandstone", "sandstone", "sandstone", "shale", "sandstone", "sandstone", "sandstone", "shale", "sandstone", "sandstone", "sandstone", "sandstone"]
  
  # Dynamic Rock Properties Models (per 02_Rock_Properties.md Section 4)
  
  # Basic rock compressibility by lithology type (matrix compressibility)
  matrix_compressibility:
    sandstone: 2.1e-6  # 1/psi (grain bulk modulus based)
    shale: 3.5e-6      # 1/psi (clay minerals based)
    limestone: 1.8e-6  # 1/psi (calcite based)
  
  # Pore volume compressibility by rock type (pressure-dependent)
  pore_compressibility:
    reference_pressure: 2000.0  # psi
    rock_types:
      RT1_high_perm_sandstone:
        compressibility: 3.5e-6  # 1/psi at reference pressure
        pressure_exponent: -0.12
        layers: [1, 2, 3, 5, 6, 7]  # Upper and middle zone sands
      RT2_medium_perm_sandstone: 
        compressibility: 4.2e-6  # 1/psi at reference pressure
        pressure_exponent: -0.15
        layers: [9, 10, 11, 12]  # Lower zone sands
      RT6_shale_barrier:
        compressibility: 12.5e-6  # 1/psi at reference pressure
        pressure_exponent: -0.35
        layers: [4, 8]  # Shale barrier layers
  
  # Stress-dependent permeability model: k(P) = k0 * exp(-gamma * (P - P0))
  # Canon values from 02_Rock_Properties.md Section 4.3 (lines 382-389)
  stress_sensitivity:
    reference_pressure: 2000.0  # psi P0
    rock_types:
      RT1_high_perm_sandstone:
        stress_coefficient: 6.2e-5  # gamma (1/psi) - Canon line 384
        reversibility_factor: 0.85  # 85% reversible - Canon line 384
        critical_stress: 3500.0  # psi (plastic deformation threshold) - Canon line 384
        layers: [1, 2, 3, 5, 6, 7]  # Upper & middle zone high quality sands
        permeability_range: [160, 175]  # mD range for RT1 layers
      RT2_medium_perm_sandstone:
        stress_coefficient: 8.5e-5  # gamma (1/psi) - Canon line 385
        reversibility_factor: 0.75  # 75% reversible - Canon line 385
        critical_stress: 3000.0  # psi - Canon line 385
        layers: [9, 10, 11, 12]  # Lower zone medium quality sands
        permeability_range: [20, 30]   # mD range for RT2 layers  
      RT6_shale_barrier:
        stress_coefficient: 35.0e-5  # gamma (1/psi) - Canon line 389 (highly stress sensitive)
        reversibility_factor: 0.15  # 15% reversible - Canon line 389
        critical_stress: 1500.0  # psi (low threshold) - Canon line 389
        layers: [4, 8]  # Shale barrier layers only
        permeability_range: [0.01, 0.01]  # mD - essentially impermeable
  
  # Porosity stress sensitivity (compaction model)
  porosity_compaction:
    rock_types:
      RT1_high_perm_sandstone:
        compaction_coefficient: 2.8e-6  # 1/psi
        plastic_threshold: 4500.0  # psi (permanent deformation)
        layers: [1, 2, 3, 5, 6, 7]
      RT2_medium_perm_sandstone:
        compaction_coefficient: 3.2e-6  # 1/psi
        plastic_threshold: 4000.0  # psi
        layers: [9, 10, 11, 12]
      RT6_shale_barrier:
        compaction_coefficient: 8.5e-6  # 1/psi
        plastic_threshold: 2000.0  # psi (low threshold)
        layers: [4, 8]
  
  # Biot poroelastic parameters for coupled flow-geomechanics
  poroelastic_parameters:
    rock_types:
      RT1_high_perm_sandstone:
        biot_coefficient: 0.72  # alpha (0.66-0.78 range)
        biot_coefficient_std: 0.06
        undrained_bulk_modulus: 2.8  # GPa
        skempton_b_parameter: 0.85
        layers: [1, 2, 3, 5, 6, 7]
      RT2_medium_perm_sandstone:
        biot_coefficient: 0.75  # alpha (0.67-0.83 range)
        biot_coefficient_std: 0.08
        undrained_bulk_modulus: 2.5  # GPa
        skempton_b_parameter: 0.82
        layers: [9, 10, 11, 12]
      RT6_shale_barrier:
        biot_coefficient: 0.88  # alpha (0.73-1.03 range)
        biot_coefficient_std: 0.15
        undrained_bulk_modulus: 3.2  # GPa
        skempton_b_parameter: 0.95
        layers: [4, 8]
  
  # Elastic properties by lithology (for geomechanical coupling)
  elastic_properties:
    sandstone:
      youngs_modulus_range: [2.5, 5.2]  # GPa
      poissons_ratio_range: [0.18, 0.28]
      youngs_porosity_correlation: [6.8, -0.15]  # E = 6.8 - 0.15*phi
      bulk_modulus_range: [1.8, 3.2]  # GPa
      shear_modulus_range: [1.2, 2.1]  # GPa
      depth_gradient: [0.15, 0.25]  # GPa/1000ft
    shale:
      youngs_modulus_range: [1.5, 8.5]  # GPa
      poissons_ratio_range: [0.25, 0.35]
      youngs_porosity_correlation: [12.0, -1.2]  # E = 12 - 1.2*phi
      bulk_modulus_range: [0.8, 5.5]  # GPa
      shear_modulus_range: [0.6, 3.2]  # GPa
      depth_gradient: [0.3, 0.6]  # GPa/1000ft