# Reservoir Field Configuration
# This file contains all reservoir properties and simulation parameters
# Modify these values to change reservoir conditions without editing code

# Grid Configuration
grid:
  nx: 20                    # Number of cells in X direction
  ny: 20                    # Number of cells in Y direction
  nz: 1                     # Number of cells in Z direction (2D simulation)
  dx: 164.0                 # Cell size in X direction [ft]
  dy: 164.0                 # Cell size in Y direction [ft]
  dz: 33.0                  # Cell thickness [ft]

# Porosity Configuration
porosity:
  base_value: 0.20          # Base porosity [-]
  variation_amplitude: 0.10  # Amplitude of spatial variation [-]
  min_value: 0.05           # Minimum allowed porosity [-]
  max_value: 0.35           # Maximum allowed porosity [-]
  correlation_length: 656.0  # Spatial correlation length [ft]
  random_amplitude_factor: 0.5  # Factor for random variation (currently hardcoded)

# Permeability Configuration
permeability:
  base_value: 100.0         # Base permeability [mD]
  variation_amplitude: 80.0  # Amplitude of spatial variation [mD]
  min_value: 10.0           # Minimum allowed permeability [mD]
  max_value: 500.0          # Maximum allowed permeability [mD]
  correlation_length: 984.0  # Spatial correlation length [ft]
  porosity_correlation: 0.8  # Correlation with porosity [-]

# Rock Properties
rock:
  reference_pressure: 2900.0  # Reference pressure [psi]
  compressibility: 3.1e-6    # Rock compressibility [1/psi]
  n_regions: 3               # Number of rock regions
  
  # Rock region thresholds (currently hardcoded in c_define_rock_regions.m)
  porosity_threshold_low: 0.18   # Tight rock threshold [-]
  porosity_threshold_high: 0.22  # Loose rock threshold [-]
  
  # Compaction coefficients by region (currently hardcoded)
  compaction_coefficients:
    region_1: 1.0e-5         # Tight rock compaction [1/psi]
    region_2: 3.0e-5         # Medium rock compaction [1/psi]
    region_3: 5.0e-5         # Loose rock compaction [1/psi]
  
  # Permeability-porosity exponents by region
  permeability_exponents:
    region_1: 8              # Tight rock k-phi exponent [-]
    region_2: 6              # Medium rock k-phi exponent [-]
    region_3: 4              # Loose rock k-phi exponent [-]
  
  # Physical bounds for porosity and permeability
  porosity_bounds:
    min: 0.01                # Minimum porosity [-]
    max: 0.50                # Maximum porosity [-]
  
  # Rock regions definition
  regions:
    - id: 1
      name: "Sandstone"
      lithology: "sandstone"
      porosity_multiplier: 1.0
      permeability_multiplier: 1.0
      compressibility: 3.1e-6
      
    - id: 2
      name: "Shale"
      lithology: "shale"
      porosity_multiplier: 0.3
      permeability_multiplier: 0.01
      compressibility: 1.4e-6
      
    - id: 3
      name: "Limestone"
      lithology: "limestone"
      porosity_multiplier: 0.7
      permeability_multiplier: 0.5
      compressibility: 2.1e-6

# Fluid Properties (structure expected by simulation scripts)
fluid:
  # Direct parameters for simulation scripts
  oil_density: 850.0        # Oil density [kg/m³]
  water_density: 1000.0     # Water density [kg/m³]
  oil_viscosity: 2.0        # Oil viscosity [cP]
  water_viscosity: 0.5      # Water viscosity [cP]
  
  # Saturation endpoints (currently hardcoded in b_define_fluid.m)
  connate_water_saturation: 0.15    # Swcon [-]
  residual_oil_saturation: 0.20     # Sores [-]
  
  # Detailed fluid properties
  oil:
    density: 850.0          # Oil density [kg/m³]
    viscosity: 2.0          # Oil viscosity [cP]
    formation_volume_factor: 1.2  # Oil FVF [-]
    compressibility: 1.0e-5  # Oil compressibility [1/psi]
    reference_pressure: 2900.0  # Reference pressure for PVT [psi]
    
  water:
    density: 1000.0         # Water density [kg/m³]
    viscosity: 0.5          # Water viscosity [cP]
    formation_volume_factor: 1.0   # Water FVF [-]
    compressibility: 3.0e-6  # Water compressibility [1/psi]
    reference_pressure: 2900.0  # Reference pressure for PVT [psi]
    
  # Relative permeability curves
  relative_permeability:
    oil:
      residual_saturation: 0.20    # Sor [-]
      endpoint_krmax: 0.90         # Maximum kro [-]
      corey_exponent: 2.0          # Corey exponent [-]
      
    water:
      connate_saturation: 0.15     # Swc [-]
      endpoint_krmax: 0.85         # Maximum krw [-]
      corey_exponent: 2.5          # Corey exponent [-]
    
    # PVT pressure range for curves
    pvt_pressure_range:
      min: 1000.0          # Minimum pressure [psi]
      max: 5000.0          # Maximum pressure [psi]
      num_points: 50       # Number of pressure points
    
    # Saturation range for kr curves
    saturation_range:
      num_points: 100      # Number of saturation points
      smoothing_factor: 0.1 # Smoothing factor for curves

# Initial Conditions
initial_conditions:
  pressure: 2900.0          # Initial reservoir pressure [psi]
  water_saturation: 0.20    # Initial water saturation [-]
  temperature: 176.0        # Reservoir temperature [°F]

# Reservoir Volumetric Data
reservoir_volumetrics:
  # Grid volume calculations
  cell_volume: 889.0        # Cell volume [ft³] (dx * dy * dz)
  total_cells: 400          # Total number of cells (nx * ny)
  total_volume: 355600.0    # Total reservoir volume [ft³]
  
  # Pore volume calculations
  average_porosity: 0.20    # Average porosity for PV calculation [-]
  total_pore_volume: 71120.0  # Total pore volume [ft³]
  
  # Oil in place calculations
  initial_oil_saturation: 0.80  # Initial oil saturation [-]
  oil_formation_volume_factor: 1.2  # Oil FVF [RB/STB]
  oil_in_place: 47413.3     # Original oil in place [STB]
  
  # Water in place calculations
  initial_water_saturation: 0.20  # Initial water saturation [-]
  water_formation_volume_factor: 1.0  # Water FVF [RB/STB]
  water_in_place: 14224.0   # Initial water in place [STB]
  
  # Conversion factors
  ft3_to_bbl: 0.178108      # ft³ to barrels conversion
  bbl_to_ft3: 5.614583      # barrels to ft³ conversion

# Boundary Conditions
boundary_conditions:
  type: "no_flow"           # Boundary type: "no_flow", "constant_pressure", "aquifer"
  pressure: 2900.0          # Boundary pressure [psi] (if applicable)

# Wells Configuration (structure expected by simulation scripts)
wells:
  # Direct parameters for simulation scripts
  producer_i: 15            # Producer grid location i-index
  producer_j: 10            # Producer grid location j-index
  producer_bhp: 2175.0      # Producer BHP [psi]
  injector_i: 5             # Injector grid location i-index
  injector_j: 10            # Injector grid location j-index
  injector_rate: 251.0      # Injector rate [bbl/day]
  
  # Detailed well configuration
  producer:
    name: "PROD1"
    location: [15, 10]      # Grid coordinates [i, j]
    type: "producer"
    control_type: "bhp"     # "bhp" or "rate"
    target_bhp: 2175.0      # Target BHP [psi]
    target_rate: 314.0      # Target rate [bbl/day] (if rate control)
    radius: 0.33            # Wellbore radius [ft]
    
  injector:
    name: "INJ1"
    location: [5, 10]       # Grid coordinates [i, j]
    type: "injector"
    control_type: "rate"    # "bhp" or "rate"
    target_bhp: 3625.0      # Target BHP [psi]
    target_rate: 251.0      # Target injection rate [bbl/day]
    radius: 0.33            # Wellbore radius [ft]
    fluid_type: "water"     # Injected fluid type

# Simulation Parameters
simulation:
  total_time: 365.0         # Total simulation time [days]
  num_timesteps: 50         # Number of timesteps
  timestep_type: "linear"   # "linear", "logarithmic", "custom"
  timestep_multiplier: 1.1  # Multiplier for increasing timesteps
  
  # Random seed for reproducibility
  random_seed: 42           # Random seed for reproducible results
  
  # Solver settings (currently hardcoded in e_run_simulation.m)
  solver:
    tolerance: 1.0e-6         # Convergence tolerance
    max_iterations: 25        # Maximum iterations per timestep
    linear_solver: "direct"   # "direct", "iterative"
    pressure_drop_factor: 0.9 # Well pressure drop factor [-]

# Geomechanical Properties
geomechanics:
  enabled: true             # Enable geomechanical coupling
  
  # Stress parameters (currently hardcoded in extract_snapshot.m)
  stress:
    surface_stress: 2000.0       # Surface total stress [psi]
    overburden_gradient: 1.0     # Overburden gradient [psi/ft]
    pore_pressure_gradient: 0.433  # Pore pressure gradient [psi/ft]
    min_horizontal_stress_ratio: 0.7  # K0 ratio [-]
    max_horizontal_stress_ratio: 1.2  # K1 ratio [-]
    min_effective_stress: 100.0  # Minimum effective stress [psi]
    
  # Mechanical properties
  mechanical:
    young_modulus: 1450000.0  # Young's modulus [psi]
    poisson_ratio: 0.25       # Poisson's ratio [-]
    biot_coefficient: 0.8     # Biot coefficient [-]

# Output Configuration
output:
  base_directory: "data/raw"  # Base output directory
  filename_prefix: "snap"     # Snapshot filename prefix
  save_format: "matlab"       # "matlab", "hdf5", "csv"
  
  # Variables to extract
  variables:
    - "effective_stress"      # σ_eff
    - "porosity"             # φ
    - "permeability"         # k
    - "rock_id"              # Rock region ID
    - "pressure"             # Pressure
    - "water_saturation"     # Sw
    
  # Snapshot grid size
  snapshot_grid:
    nx: 20                   # Snapshot grid cells in X
    ny: 20                   # Snapshot grid cells in Y

# Metadata
metadata:
  project_name: "MRST Geomechanical Simulation"
  description: "2D reservoir simulation with geomechanical coupling"
  author: "Simulation Team"
  version: "1.0"
  created_date: "2025-01-15"
  units:
    length: "feet"
    pressure: "psi"
    permeability: "millidarcy"
    time: "days"
    temperature: "fahrenheit"
    volume: "barrels"
    rate: "barrels_per_day"
    
  # Unit conversion factors (currently hardcoded in scripts)
  conversion_factors:
    ft_to_m: 0.3048               # Feet to meters
    psi_to_pa: 6894.76            # PSI to Pascals
    md_to_m2: 9.869233e-16        # Millidarcy to m²
    bbl_per_day_to_m3_per_s: 1.589873e-7  # bbl/day to m³/s
    cp_to_pa_s: 1.0e-3            # Centipoise to Pa·s
    days_to_seconds: 86400        # Days to seconds
    m_to_ft: 3.28084              # Meters to feet 